/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.13.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as articles from "../articles.js";
import type * as auth from "../auth.js";
import type * as breakingNews from "../breakingNews.js";
import type * as dailyBrief from "../dailyBrief.js";
import type * as liveStreams from "../liveStreams.js";
import type * as models from "../models.js";
import type * as newsletters from "../newsletters.js";
import type * as podcasts from "../podcasts.js";
import type * as submissions from "../submissions.js";
import type * as users from "../users.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

/**
 * A utility for referencing Convex functions in your app's API.
 */
declare const fullApi: ApiFromModules<{
  articles: typeof articles;
  auth: typeof auth;
  breakingNews: typeof breakingNews;
  dailyBrief: typeof dailyBrief;
  liveStreams: typeof liveStreams;
  models: typeof models;
  newsletters: typeof newsletters;
  podcasts: typeof podcasts;
  submissions: typeof submissions;
  users: typeof users;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
